"""
cogs/fit_edit.py — Fit image into asset region commands
─────────────────────────────────────────────────────────
Commands are loaded from commands/fit_commands.json.
Do not edit this file to add commands — edit fit_commands.json instead.
"""

import os
import time
import json
import traceback
import discord
from discord import app_commands
from discord.ext import commands
from utils.image_fit import fetch_image, fit_image, find_image_in_message

ROOT   = os.path.join(os.path.dirname(__file__), "..")
ASSETS = os.path.join(ROOT, "assets")

with open(os.path.join(ROOT, "commands", "fit_commands.json"), "r") as f:
    FIT_COMMANDS = json.load(f)


async def run_fit(ctx_or_interaction, asset_path, region, layer="behind",
                  target=None, is_interaction=False, image_url=None):

    async def send(content=None, file=None):
        if is_interaction:
            await ctx_or_interaction.followup.send(content=content, file=file)
        else:
            await ctx_or_interaction.send(content=content, file=file)

    if is_interaction:
        try:
            await ctx_or_interaction.response.defer()
        except Exception as e:
            print(f"[ERROR] defer() failed: {e}")
            traceback.print_exc()
            return

    if image_url is None:
        if target is not None:
            image_url = target.display_avatar.with_format("png").with_size(512).url
        else:
            if is_interaction:
                try:
                    channel = ctx_or_interaction.channel
                    if channel is not None:
                        async for prev in channel.history(limit=10):
                            image_url = find_image_in_message(prev)
                            if image_url:
                                break
                except discord.Forbidden:
                    await ctx_or_interaction.followup.send(
                        "❌ I can't read message history here. Use `user:` or `image:` instead!"
                    )
                    return
                except Exception as e:
                    print(f"[ERROR] history scan failed: {e}")
                    traceback.print_exc()
            else:
                ctx = ctx_or_interaction
                if ctx.message.reference:
                    try:
                        ref = ctx.message.reference.resolved or await ctx.channel.fetch_message(
                            ctx.message.reference.message_id
                        )
                        image_url = find_image_in_message(ref)
                        if image_url is None:
                            image_url = ref.author.display_avatar.with_format("png").with_size(512).url
                    except Exception:
                        pass
                if image_url is None:
                    async for prev in ctx.channel.history(limit=10, before=ctx.message):
                        image_url = find_image_in_message(prev)
                        if image_url:
                            break

    if image_url is None:
        await send("❌ Couldn't find an image. Attach one, reply to one, or pass a `user:`!")
        return

    try:
        t0       = time.monotonic()
        base     = await fetch_image(image_url)
        buf, ext = fit_image(base, asset_path, region, layer=layer)
        elapsed  = time.monotonic() - t0
        await send(
            content=f"this task completed in {elapsed:.2f} seconds.",
            file=discord.File(buf, filename=f"result.{ext}"),
        )
    except Exception as e:
        print(f"[ERROR] fit failed: {e}")
        traceback.print_exc()
        await send(f"❌ Something went wrong: `{e}`")


def make_context_callback(asset, region, layer):
    """Creates a clean context menu callback with bound asset/region/layer."""
    async def callback(interaction: discord.Interaction, message: discord.Message):
        image_url = find_image_in_message(message)
        if image_url is None:
            image_url = message.author.display_avatar.with_format("png").with_size(512).url
        await run_fit(interaction, asset, region, layer=layer,
                      is_interaction=True, image_url=image_url)
    return callback


class FitEdit(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self._choices = [
            app_commands.Choice(name=e["command"], value=e["command"])
            for e in FIT_COMMANDS
        ]
        self._entries = {
            e["command"]: {
                "asset":  os.path.join(ASSETS, e["asset"]),
                "region": e["region"],
                "layer":  e.get("layer", "behind"),
            }
            for e in FIT_COMMANDS
        }
        self._register_prefix_commands()
        self._register_slash_command()
        self._register_context_menu_commands()

    def _register_prefix_commands(self):
        for entry in FIT_COMMANDS:
            asset_path = os.path.join(ASSETS, entry["asset"])
            region     = entry["region"]
            layer      = entry.get("layer", "behind")

            async def callback(ctx, target: discord.Member = None,
                               _asset=asset_path, _region=region, _layer=layer):
                await run_fit(ctx, _asset, _region, layer=_layer,
                              target=target, is_interaction=False)

            self.bot.add_command(commands.Command(
                callback, name=entry["command"], help=entry["help"]
            ))

    def _register_slash_command(self):
        choices = self._choices
        entries = self._entries

        @app_commands.command(name="shitpostbot_fit", description="ShitPostBot fit-image commands")
        @app_commands.allowed_installs(guilds=True, users=True)
        @app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
        @app_commands.describe(
            command="Which command to run",
            user="(Optional) Target user — uses their avatar",
            image="(Optional) Upload an image directly",
        )
        @app_commands.choices(command=choices)
        async def fit_slash(
            interaction: discord.Interaction,
            command: app_commands.Choice[str],
            user: discord.User = None,
            image: discord.Attachment = None,
        ):
            try:
                print(f"[DEBUG] /shitpostbot_fit called — command={command.value} user={user} image={image}")
                entry = entries.get(command.value)
                if not entry:
                    await interaction.response.send_message("❌ Unknown command.", ephemeral=True)
                    return
                image_url = image.url if image else None
                await run_fit(interaction, entry["asset"], entry["region"],
                              layer=entry["layer"], target=user, is_interaction=True, image_url=image_url)
            except Exception as e:
                print(f"[ERROR] top-level slash error: {e}")
                traceback.print_exc()
                try:
                    await interaction.response.send_message(f"❌ Error: `{e}`", ephemeral=True)
                except Exception:
                    try:
                        await interaction.followup.send(f"❌ Error: `{e}`", ephemeral=True)
                    except Exception:
                        pass

        self.bot.tree.add_command(fit_slash)

    def _register_context_menu_commands(self):
        entries = self._entries

        for entry in FIT_COMMANDS:
            if not entry.get("context_menu", False):
                continue

            e      = entries[entry["command"]]
            name   = entry["command"]
            cb     = make_context_callback(e["asset"], e["region"], e["layer"])

            cmd = app_commands.ContextMenu(name=name, callback=cb)
            cmd.allowed_installs = app_commands.AppInstallationType(guild=True, user=True)
            cmd.allowed_contexts = app_commands.AppCommandContext(
                guild=True, dm_channel=True, private_channel=True
            )
            self.bot.tree.add_command(cmd)


async def setup(bot):
    await bot.add_cog(FitEdit(bot))
