"""
cogs/slap_edit.py — Image slap commands
─────────────────────────────────────────
Commands are loaded from commands/slap_commands.json.
Do not edit this file to add commands — edit slap_commands.json instead.
"""

import os
import time
import random
import json
import traceback
import discord
from discord import app_commands
from discord.ext import commands
from utils.image_slap import fetch_image, slap_image, find_image_in_message

ROOT   = os.path.join(os.path.dirname(__file__), "..")
ASSETS = os.path.join(ROOT, "assets")

with open(os.path.join(ROOT, "commands", "slap_commands.json"), "r") as f:
    SLAP_COMMANDS = json.load(f)


async def run_slap(ctx_or_interaction, asset_pool, target=None, is_interaction=False, image_url=None):

    async def send(content=None, file=None):
        if is_interaction:
            await ctx_or_interaction.followup.send(content=content, file=file)
        else:
            await ctx_or_interaction.send(content=content, file=file)

    if is_interaction:
        try:
            await ctx_or_interaction.response.defer()
        except Exception as e:
            print(f"[ERROR] defer() failed: {e}")
            traceback.print_exc()
            return

    if image_url is None:
        if target is not None:
            image_url = target.display_avatar.with_format("png").with_size(512).url
        else:
            if is_interaction:
                try:
                    channel = ctx_or_interaction.channel
                    if channel is not None:
                        async for prev in channel.history(limit=10):
                            image_url = find_image_in_message(prev)
                            if image_url:
                                break
                except discord.Forbidden:
                    await ctx_or_interaction.followup.send(
                        "❌ I can't read message history here. Use `user:` or `image:` instead!"
                    )
                    return
                except Exception as e:
                    print(f"[ERROR] history scan failed: {e}")
                    traceback.print_exc()
            else:
                ctx = ctx_or_interaction
                if ctx.message.reference:
                    try:
                        ref = ctx.message.reference.resolved or await ctx.channel.fetch_message(
                            ctx.message.reference.message_id
                        )
                        image_url = find_image_in_message(ref)
                        if image_url is None:
                            image_url = ref.author.display_avatar.with_format("png").with_size(512).url
                    except Exception:
                        pass
                if image_url is None:
                    async for prev in ctx.channel.history(limit=10, before=ctx.message):
                        image_url = find_image_in_message(prev)
                        if image_url:
                            break

    if image_url is None:
        await send("❌ Couldn't find an image. Attach one, reply to one, or pass a `user:`!")
        return

    try:
        t0       = time.monotonic()
        base     = await fetch_image(image_url)
        asset    = random.choice(asset_pool)
        buf, ext = slap_image(base, asset)
        elapsed  = time.monotonic() - t0
        await send(
            content=f"this task completed in {elapsed:.2f} seconds.",
            file=discord.File(buf, filename=f"result.{ext}"),
        )
    except Exception as e:
        print(f"[ERROR] slap failed: {e}")
        traceback.print_exc()
        await send(f"❌ Something went wrong: `{e}`")


def make_context_callback(pool):
    """Creates a clean context menu callback with bound asset pool."""
    async def callback(interaction: discord.Interaction, message: discord.Message):
        image_url = find_image_in_message(message)
        if image_url is None:
            image_url = message.author.display_avatar.with_format("png").with_size(512).url
        await run_slap(interaction, pool, is_interaction=True, image_url=image_url)
    return callback


class SlapEdit(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self._choices = [
            app_commands.Choice(name=e["command"], value=e["command"])
            for e in SLAP_COMMANDS
        ]
        self._pools = {
            e["command"]: [
                os.path.join(ASSETS, f)
                for f in (e["asset"] if isinstance(e["asset"], list) else [e["asset"]])
            ]
            for e in SLAP_COMMANDS
        }
        self._register_prefix_commands()
        self._register_slash_command()
        self._register_context_menu_commands()

    def _register_prefix_commands(self):
        for entry in SLAP_COMMANDS:
            pool = self._pools[entry["command"]]

            async def callback(ctx, target: discord.Member = None, _pool=pool):
                await run_slap(ctx, _pool, target=target, is_interaction=False)

            self.bot.add_command(commands.Command(
                callback, name=entry["command"], help=entry["help"]
            ))

    def _register_slash_command(self):
        choices = self._choices
        pools   = self._pools

        @app_commands.command(name="shitpostbot", description="ShitPostBot image commands")
        @app_commands.allowed_installs(guilds=True, users=True)
        @app_commands.allowed_contexts(guilds=True, dms=True, private_channels=True)
        @app_commands.describe(
            command="Which command to run",
            user="(Optional) Target user — uses their avatar",
            image="(Optional) Upload an image directly",
        )
        @app_commands.choices(command=choices)
        async def shitpostbot_slash(
            interaction: discord.Interaction,
            command: app_commands.Choice[str],
            user: discord.User = None,
            image: discord.Attachment = None,
        ):
            try:
                print(f"[DEBUG] /shitpostbot called — command={command.value} user={user} image={image}")
                pool = pools.get(command.value)
                if not pool:
                    await interaction.response.send_message("❌ Unknown command.", ephemeral=True)
                    return
                # image attachment takes priority over user
                image_url = image.url if image else None
                await run_slap(interaction, pool, target=user, is_interaction=True, image_url=image_url)
            except Exception as e:
                print(f"[ERROR] top-level slash error: {e}")
                traceback.print_exc()
                try:
                    await interaction.response.send_message(f"❌ Error: `{e}`", ephemeral=True)
                except Exception:
                    try:
                        await interaction.followup.send(f"❌ Error: `{e}`", ephemeral=True)
                    except Exception:
                        pass

        self.bot.tree.add_command(shitpostbot_slash)

    def _register_context_menu_commands(self):
        pools = self._pools

        for entry in SLAP_COMMANDS:
            if not entry.get("context_menu", False):
                continue

            pool = pools[entry["command"]]
            name = entry["command"]
            cb   = make_context_callback(pool)

            cmd = app_commands.ContextMenu(name=name, callback=cb)
            cmd.allowed_installs = app_commands.AppInstallationType(guild=True, user=True)
            cmd.allowed_contexts = app_commands.AppCommandContext(
                guild=True, dm_channel=True, private_channel=True
            )
            self.bot.tree.add_command(cmd)


async def setup(bot):
    await bot.add_cog(SlapEdit(bot))
